sudo: required

notifications:
  email: false

language: go

go:
  - "1.8"
  - "1.9"
#  - "tip"

services:
  - docker
  - postgresql

addons:
  postgresql: 9.5
  apt:
    packages:
    - freetds-bin

env:
  global:
    - MAKEFLAGS="-j4"
    - GOARCH=amd64
    - DB_HOST=127.0.0.1
  matrix:
    - TEST_CMD="make benchmark test-main"
    - TEST_CMD="make test-adapters"

install:
  - mkdir -p $GOPATH/src/github.com/acoshift
  - mv $PWD $GOPATH/src/github.com/acoshift/db
  - cd $GOPATH/src/github.com/acoshift/db
  - go get -t -v -d ./...
  - go get -v github.com/cznic/ql/ql
  - export TRAVIS_BUILD_DIR=$GOPATH/src/github.com/acoshift/db

script:
  - ${TEST_CMD}
